variable "name" {}
variable "env" {}
variable "instance_type" {}
variable "subnet_ids" {}
variable "vpc_id" {}
variable "allow_app_cidr" {}
variable "bastion_cidr" {}
variable "desired_capacity" {}
variable "max_size" {}
variable "min_size" {}
variable "tags" {}
variable "app_port" {}